### ISSUE TITLE
German translation: wrong constellations shown

### ISSUE THREAD

**Issue by MisterTeatime** [Treeki/MeteoNook#14]
In the german translation the wrong constellation is shown.

![image](https://user-images.githubusercontent.com/13699856/87725467-a8070480-c7bd-11ea-8461-1c5b60e66eaa.png)
Now: Capricorn
Next: Aquarius

English is correct
![image](https://user-images.githubusercontent.com/13699856/87725561-ca991d80-c7bd-11ea-8749-c2a8389ba876.png)

The offset seems to be exactly 6 months, because the sequence is correct (capricorn preceeds aquarius, but in January/February)

**Comment by MisterTeatime** [comment]
Cause seems to be, that the constellation list in German is different and jumbled compared to english.

current EN (correct): Capricorn%%Aquarius%%Pisces%%Aries%%Taurus%%Gemini%%Cancer%%Leo%%Virgo%%Libra%%Scorpio%%Sagittarius
EN in DE: Steinbock%%Wassermann%%Fische%%Widder%%Stier%%Zwillinge%%Krebs&&Löwe%%Jungfrau%%Waage%%Skorpion%%Schütze

current DE (wrong, for reference): Widder%%Stier%%Zwillinge%%Krebs%%Löwe%%Jungfrau%%Steinbock%%Wassermann%%Fische%%Waage%%Skorpion%%Schütze
DE in EN: Aries%%Gemini%%Cancer%%Leo%%Virgo%%Capricorn%%Aquarius%%Pisces%%Libra%%Scorpio%%Sagittarius

**Comment by Treeki** [comment]
fixed in POEditor, will be in the live app next time I sync translations
