### ISSUE TITLE
French translation: constellations offset

### ISSUE THREAD

**Issue by MisterTeatime** [Treeki/MeteoNook#15]
Basically the same issue as the German translation. The order of constellations differes from the English order.

current EN (correct): Capricorn%%Aquarius%%Pisces%%Aries%%Taurus%%Gemini%%Cancer%%Leo%%Virgo%%Libra%%Scorpio%%Sagittarius
EN in FR: Capricorne%%Verseau%%Poisson%%Bélier%%Taureau%%Gémeaux%%Cancer%%Lion%%Vierge%%Balance%%Scorpion%%Sagittaire

current FR (wrong): Verseau%%Poisson%%Bélier%%Taureau%%Gémeaux%%Cancer%%Lion%%Vierge%%Balance%%Scorpion%%Sagittaire%%Capricorne

ciruclar order is correct, starting point should be Capricorne (now last element)

**Comment by Treeki** [comment]
fixed on POEditor, will be in the app the next time I sync translations
