### ISSUE TITLE
KK affects the weather?

### ISSUE THREAD

**Issue by tukete** [Treeki/MeteoNook#17]
I found my seed and everything was accurate until today, but tonight I must have pattern FineCloud02. What does mean rain in the evening, but it's not. Is the problem in the pattern or because of the KK concert today?

**Comment by Starwort** [comment]
Have you had any meteor showers that corroborate the seed? If not, consider the possibility that your seed is wrong (I myself had issues with my star timing because my switch is 5 seconds off lol)

**Comment by tukete** [comment]
All meteor showers (1 heavy and 2 light) were on time, minute to minute. 2 rainbows too. And everything until yesterday was accurate.

**Comment by Treeki** [comment]
if it’s your first KK Slider concert, then that will force EventDay00 weather for one or two days - this is mentioned on the Tips section in the Seed tab

**Comment by tukete** [comment]
It's not his first concert.
