### ISSUE TITLE
Static clouds in background

### ISSUE THREAD

**Issue by im33l** [Treeki/MeteoNook#23]
The background of the game (the horizon) sometimes shows almost static clouds which changes the way you can "read" the weather.

Are the moving clouds on the top of the sky the only ones that matter? Or do we have to keep the clouds on the horizon in mind?

![20200725_162409](https://user-images.githubusercontent.com/68781340/88459135-49174e80-ce93-11ea-9807-4f612120316b.jpg)

**Comment by im33l** [comment]
after staring at the static clouds for minutes at an end i noticed they are moving! (Veeeery slowly to the left. Where the other clouds move to the right)

**Comment by Treeki** [comment]
These are special cloud types which only appear during certain parts of the year, and are unrelated to the main weather types. I haven't added info to MeteoNook about them yet as I need to do more research on precisely how they work.

**Comment by Treeki** [comment]
App has now been updated with predictions and seed searching using the special cloud types.
