### ISSUE TITLE
Shooting Stars Times in summary don't match times in details

### ISSUE THREAD

**Issue by rasppliances** [Treeki/MeteoNook#27]
Once you've done your search and received your possible seed, you get a summary block that gives today's weather.  If there will be shooting starts, it shows times you're likely to see them.  If  you then click the See more button to look at the details, the times for shooting stars don't match with the times from the summary.

![shooting stars](https://user-images.githubusercontent.com/2730583/89037081-e1865680-d30b-11ea-89df-2801c15002fe.png)

**Comment by Small-Ku** [comment]
Duplicated. See #8 .

**Comment by rasppliances** [comment]
I added a comment to #8.  This gives a very mixed signal.  We're supposed to track our showers to the second when entering data, but then only see an average of times when we first look at the expected weather.  Obviously you can't give details in such a small space, but it would be much more consistent with tracking things to the second to offer a range of "7:07-7:15" instead of seeing "7:10".  Then, at least they would match with the detailed view.
