### ISSUE TITLE
[feature request] Mystery island weather forecast

### ISSUE THREAD

**Issue by bbyam** [Treeki/MeteoNook#31]
Feature suggestion:

Anecdotal evidence suggests mystery islands have a weather pattern as well, just different from the home island weather (visiting multiple mystery islands during the same hour, they all have the same weather).

If mystery island weather is somehow based on the same seed, it could be forecast as well.

Knowing when it will be raining on a mystery island can be useful for fishing and increasing scorpion spawns.

**Comment by Treeki** [comment]
You can already do this in MeteoNook by adding your mystery island as a separate island entry. They use a distinct weather setting with a different seed, but the selection algorithm should be the same.
