### ISSUE TITLE
Overview page showing wrong minutes for shootings stars. 'See More' page is correct.

### ISSUE THREAD

**Issue by zeroum** [Treeki/MeteoNook#32]
Example: https://wuffs.org/acnh/weather/?v1&Naturae&311076505&S

I can confirm the See More page  minutes and seconds in-game.

----

Overview:

Today

🌤 Clear all day

🌠 Expect some shooting stars around 19:18, 19:53, 20:22, 20:43, 21:10, 22:09, 22:37, 23:01, 23:39, 00:58, 01:22, 02:49 and 03:43

August 5, 2020
Pattern: Fine04

----

See More:

19:00: 🍃0 🌤 Sunny

🌠 19:18 - :16, :19, :43, :50, :58

🌠 19:48 - :05, :17, :21, :29, :40

🌠 19:49 - :06, :13, :28, :36, :52

20:00: 🍃1 🌤 Sunny

🌠 20:01 - :30, :34, :36, :42, :59

🌠 20:22 - :19, :28, :39, :57, :58

🌠 20:43 - :03, :21, :25, :49, :52

21:00: 🍃2 ☀ Clear/Fine

🌠 21:07 - :04, :18, :21, :25, :38

🌠 21:12 - :04, :13, :27, :41, :49

**Comment by demosdemon** [comment]
Dupe #8 #27
