### ISSUE TITLE
[feature request] Make a .ical available for the calendar

### ISSUE THREAD

**Issue by hexylena** [Treeki/MeteoNook#36]
I'd love to be able to add MeteoNook's reporting into my calendar or similar, so I can take advantage of the notifications there for when the big events like the next heavy star shower/aurora/double rainbows are. I imagine that a file can be generated on the fly in memory, and a download triggered for that.

**Comment by forbesjo** [comment]
~~Looks like https://github.com/adamgibbons/ics could be useful~~

https://github.com/Treeki/MeteoNook/pull/29 is on it

**Comment by hexylena** [comment]
Oh, fantastic, I should have checked the open PRs. Super cool. Well, this issue isn't so relevant if it's WIP :)
