### ISSUE TITLE
No event day weather on October 31st?

### ISSUE THREAD

**Issue by ajf8729** [Treeki/MeteoNook#40]
Wasn't sure if this was an issue or not, but I noticed that I'm scheduled to have a meteor shower on October 31st. I figured this day would have the typical "event day weather". Northern hemisphere, seed is 194650881

**Comment by Staleknight** [comment]
Same thing here. I’ve got a meteor shower that’s being overridden by the Halloween weather pattern. Would love to see the app updated with the new pattern so I don’t waste time looking for meteors that won’t show up in the future.

My game is on the northern hemisphere with seed 1825855269.
