### ISSUE TITLE
Not able to find seed as of ACNH version 1.6.0

### ISSUE THREAD

**Issue by TanteTimmie** [Treeki/MeteoNook#42]
As of version 1.4.0 I had no problem getting the seeds for my own ACNH game and 2 of my friends. 

My gf started playing in August. Through september/october I entered weatherinfo for her game. Couldn't find the correct seed. 

Last week I only entered Celeste visits and the  (announced by Isabelle) meteor shower information she had from her island. This to be sure there was no incorrect entered info possible. I am 100% sure this information is all correct. It's down to 2 possible seeds now. Both are not properly refelecting the weather she is having on her island today.

I assume something was changed in update 1.5 or 1.6 that makes it impossible to get the correct weatherseed for islands.

**Comment by willcoff** [comment]
i am having the same problem. just looked at his twitter and he apparently is not doing anything with acnh anymore.

**Comment by mhedrick** [comment]
seeing the same issue

**Comment by superfucky** [comment]
My weather has stopped being accurate for my seed (1258030453) as of this afternoon, and I noticed a week ago that I get different forecasts for 2021 depending on whether I'm viewing on mobile or desktop. 
![meteonookdesktop](https://user-images.githubusercontent.com/76600926/103142859-fd323500-46d0-11eb-89b6-a674e9a9ff94.png)
![meteonookmobile](https://user-images.githubusercontent.com/76600926/103142860-00c5bc00-46d1-11eb-98b2-9a5b9aa6cb54.png)

**Comment by papjul** [comment]
I have the same issue with predictions on 2021 or on 1.6.0. Some predictions are correct, some are wrong. Seed is correct.

I don't have any difference between desktop and mobile.
@superfucky Is one of them correct? Could you let us know if your mobile is running 32-bit (mostly old devices)? If you don't know where to find it, what is your phone model?

Both my devices are 64-bit which may be the reason why results are showing wrong (basically, only 32-bit numbers are manipulated in the source code).

**Comment by TanteTimmie** [comment]
I've noticed in the seed on the island that is still working/mostly correct event days are not included/being reflected in the seed predictions.

**Comment by papjul** [comment]
Yes, there has been multiple issues regarding the event days. The issue I mention is unrelated, I have the issue today, which is not an event day. All star minutes predictions were correct today on the 19th hour, and all were incorrect on the 21th hour.

**Comment by superfucky** [comment]
my phone's new so it's not that. also whatever was causing the issue seems to have been corrected - i now see the same forecasts for daily, monthly & yearly views on both mobile & desktop. previously the yearly view was showing 2020's forecast regardless of which year i selected, daily view was accurate on both platforms, and monthly view would show meteor showers correctly but mislabeled daily weather patterns & used incorrect emojis.

however, like i said, that seems to have been corrected as of this morning! i hard-refreshed on desktop and everything looks correct on both platforms.

**Comment by TanteTimmie** [comment]
I just hope meteonook will be continued with the AC updates. As it is now seeds can't be found for islands. Too bad.

**Comment by papjul** [comment]
False positive on my side, I just recall that creating a character changes the weather.
So, basically what I did:
19:00: stars
20:00: created a character, weather changed
21:00: no stars from now on :(

**Comment by TanteTimmie** [comment]
Closing my issue as lots of new issues that deserve their own posts get posted on this thread... Since I am not a developer and just a user... Just gotta wait till the developer does something with meteonook again.

**Comment by ELY3M** [comment]
Sadly, the developer stopped working on this project.
