### ISSUE TITLE
Update to ACHH 1.10.0

### ISSUE THREAD

**Issue by JasonP2018** [Treeki/MeteoNook#61]
This thing needs to be updated from 1.4.0 to 1.10.0 because it is no longer right in 1.10.0

**Comment by AtlantisStuart** [comment]
Agree. I have a meteor shower today and after I tracked every meteor (up to min) so far I cannot get my matching seed

**Comment by JasonPau2018** [comment]
Yea me too

**Comment by ELY3M** [comment]
you can get your seed via using NHSE if you have CFW running on your switch and can get your game saves with JKSV.  

the developer stopped working on this project

**Comment by tjsky** [comment]
I  get my matching seed in 1.11.0 ，just now

**Comment by JasonP2018** [comment]
They may have changed it

**Comment by JasonP2018** [comment]
I just have got my weather seed right so I think they updated AC:NH so now it works fine
