### ISSUE TITLE
The overview tab should give the time of stars

### ISSUE THREAD

**Issue by plallin** [Treeki/MeteoNook#9]
The overview tab currently gives the following information:
- summary of today's weather
- summary of tomorrow's weather
- weather events coming up such as rainbows and heavy star showers
- information about constellation

All of this is nice to see in a glance, however there is an information that is missing from me on this overview tab: it does not show the upcoming minor star showers. I have to find out about them in the monthly tab instead.

I think the "today" and "tomorrow" summary in overview could be enriched by showing (1) whether there is any stars on that day and (2) the time of the shower.

**Comment by Starwort** [comment]
Press the 'see more' button to show the full weather for that day, including the minor stars, and it will tell you some of the stars anyway

**Comment by Treeki** [comment]
It already does this as of a few days ago - the Today and Tomorrow cards show light showers along with the times of star clusters. Is this not showing up for you?

**Comment by plallin** [comment]
It does now :)
